# Generated by Django 4.0.1 on 2022-01-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_geolocation_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geolocation',
            options={'verbose_name': '', 'verbose_name_plural': ''},
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='ip',
            field=models.CharField(max_length=39, unique=True, verbose_name='ip address'),
        ),
    ]
